version: "3.9"

volumes:
  tosca-2-geoserver-deployment-dev:
  tosca-2-geo-db-data-deployment-dev:

services:
  db:
    image: kartoza/postgis:${POSTGIS_VERSION_TAG}
    container_name: tosca-2-db-deployment-container
    volumes:
      - tosca-2-geo-db-data-deployment-dev:/var/lib/postgresql
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASS=${POSTGRES_PASS}
      - ALLOW_IP_RANGE=${ALLOW_IP_RANGE}
      - FORCE_SSL=TRUE
    restart: on-failure
    healthcheck:
      test: "PGPASSWORD=${POSTGRES_PASS} pg_isready -h 127.0.0.1 -U ${POSTGRES_USER} -d ${POSTGRES_DB}"

  geoserver:
    image: orttak/tosca-geoserver
    container_name: tosca-2-geoserver-deployment-container
    volumes:
      - tosca-2-geoserver-deployment-dev:/usr/share/geoserver/data_dir
      - /home/akif/Desktop/HCU/TOSCA-2/data:/mnt/data
      # - LOCAL_FOLDER_FULL_PATH:/mnt/data
    ports:
      - ${GEOSERVER_PORT}:8080

  tosca-web:
    build:
      context: .
      dockerfile: Dockerfile
    image: tosca-2-deployment-dev:latest
    container_name: tosca-2-web-deployment-dev-container
    ports:
      - 8181:80
