version: "3.9"

volumes:
  tosca-2-geoserver-deployment-production:
  tosca-2-geo-db-data-deployment-production:

services:
  db:
    image: kartoza/postgis:${POSTGIS_VERSION_TAG}
    container_name: tosca-2-db-production-container
    volumes:
      - tosca-2-geo-db-data-production:/var/lib/postgresql
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASS=${POSTGRES_PASS}
      - ALLOW_IP_RANGE=${ALLOW_IP_RANGE}
      - FORCE_SSL=TRUE
    restart: on-failure
    healthcheck:
      test: "PGPASSWORD=${POSTGRES_PASS} pg_isready -h 127.0.0.1 -U ${POSTGRES_USER} -d ${POSTGRES_DB}"

  geoserver:
    image: orttak/tosca-geoserver-production:latest
    container_name: tosca-2-geoserver-production-container
    volumes:
      - tosca-2-geoserver-production:/usr/share/geoserver/data_dir
      - LOCAL_FOLDER_FULL_PATH:/mnt/data
    ports:
      - ${GEOSERVER_PORT}:8080
  tosca-web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    image: tosca-production-dev:latest
    container_name: tosca-2-web-production-container
    ports:
      - 80:80
